"""
Patterns from the DeepReason / deep_reasoning_researcher project: planner + critic only.

We use the *planner* idea (break the user question into targeted web search strings) and the
*critic* idea (judge whether gathered snippets look sufficient vs. needing more search).

No LangGraph loop, Tavily, researcher node, or writer — see upstream:
https://github.com/themiccc/deep_reasoning_researcher
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class SearchTaskItem(BaseModel):
    """One planner task: search string, facet label, and expanded research intent (DeepReason-style)."""

    query: str = Field(description="Web search string for a single facet; suitable for a search engine.")
    goal: str = Field(
        description="One short line (max ~140 chars), unique per task: the facet label / angle this query covers."
    )
    research_objective: str = Field(
        default="",
        description=(
            "Expanded research goal (2–6 sentences), like deep_reasoning_researcher’s planner: "
            "what this search must establish, what evidence would satisfy it, and how it connects "
            "to the user’s original question. Do not paste the search query verbatim; explain intent."
        ),
    )


class SearchTaskPlan(BaseModel):
    rationale: str = Field(description="Briefly why these search tasks cover the user's question.")
    tasks: list[SearchTaskItem] = Field(description="Distinct tasks; each goal must be unique to its query.", min_length=1)

FRAMEWORK_URL = "https://github.com/themiccc/deep_reasoning_researcher"

# Mirrors nodes.planner_node intent: distinct, specific search strings for the web.
_PLANNER_SYSTEM = """You are a research planner (DeepReason-style; see github.com/themiccc/deep_reasoning_researcher).
Break the user's question into separate, specific web search queries that together could
support a comprehensive answer. Each query must target one angle; avoid near-duplicates.

For EVERY task you MUST provide:
- `goal`: one short unique line — the facet label only.
- `research_objective`: a fuller paragraph (2–6 sentences) that stands alone: what this search
  should establish, what “good” sources would demonstrate, and how this facet supports answering
  the user’s original question. This must NOT duplicate `goal` word-for-word — it is the expanded
  research intent, not a second short label.

Prefer fewer queries when one search is enough; use up to the allowed maximum when the question
truly needs multiple facets. Output only structured fields per the schema."""


def plan_search_tasks(query: str, n: int, client: Any) -> dict | None:
    """
    Returns { sub_queries: [{query, goal}], rationale: str, source: str } or None on failure.
    """
    if client is None:
        return None
    try:
        user_msg = (
            f"User question:\n{query.strip()}\n\n"
            f"Maximum number of search tasks: {n}\n"
            "Return at least 1 task and at most the maximum. "
            "Each task needs `query`, `goal` (short facet label), and `research_objective` "
            "(expanded paragraph: intent, success criteria, link to the user question)."
        )
        plan = client.chat.completions.create(
            model="gpt-4o-mini",
            response_model=SearchTaskPlan,
            messages=[
                {"role": "system", "content": _PLANNER_SYSTEM},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.35,
            timeout=14,
        )
        rationale_text = (plan.rationale or "").strip()
        raw_tasks = list(plan.tasks or [])[:n]
        seen: set[str] = set()
        out_sq: list[dict] = []
        for t in raw_tasks:
            q = (t.query or "").strip()
            if not q:
                continue
            k = q.casefold()
            if k in seen:
                continue
            seen.add(k)
            g = (t.goal or "").strip() or f"Search angle: {q[:120]}"
            ro = (t.research_objective or "").strip()
            if not ro:
                ro = (
                    f"Establish material that supports the user’s question via this facet ({g}). "
                    f"Use web results to gather verifiable facts and context; prefer authoritative "
                    f"industry, regulatory, or trade sources where relevant."
                )
            out_sq.append({"query": q, "goal": g[:400], "research_objective": ro[:2000]})
        if not out_sq:
            return None
        return {
            "sub_queries": out_sq,
            "rationale": rationale_text or "Search tasks generated by the planner.",
            "source": "deep_reasoning_researcher_planner",
        }
    except Exception as e:
        logger.debug("plan_search_tasks failed: %s", e)
        return None


_FOLLOWUP_PLANNER_SYSTEM = """You are a research planner (DeepReason-style).
The user's question was already researched with an initial set of queries, but the
critic found gaps. Generate NEW search queries that cover missing aspects. Do NOT repeat
or rephrase queries already tried (listed in the user message).

For each task provide `query`, `goal` (short facet label), and `research_objective` (2–6 sentences:
what this follow-up must establish and how it fills the gap for the original question).
Output only structured fields per the schema."""


def plan_followup_tasks(
    original_query: str,
    already_tried: list[str],
    n: int,
    client: Any,
) -> dict | None:
    """
    Like plan_search_tasks but instructs the planner to avoid already-tried queries.
    Returns { sub_queries: [{query, goal}], rationale: str, source: str } or None on failure.
    """
    if client is None:
        return None
    try:
        tried_block = "\n".join(f"  - {q}" for q in already_tried)
        user_msg = (
            f"Original question:\n{original_query.strip()}\n\n"
            f"Queries already tried (do NOT repeat or rephrase these):\n{tried_block}\n\n"
            f"Maximum number of NEW search tasks: {n}\n"
            "Return at least 1 new task and at most the maximum. "
            "Each task needs `query`, `goal`, and `research_objective`. "
            "Queries must target aspects NOT covered by the already-tried list."
        )
        plan = client.chat.completions.create(
            model="gpt-4o-mini",
            response_model=SearchTaskPlan,
            messages=[
                {"role": "system", "content": _FOLLOWUP_PLANNER_SYSTEM},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.35,
            timeout=14,
        )
        rationale_text = (plan.rationale or "").strip()
        raw_tasks = list(plan.tasks or [])[:n]
        tried_lower = {q.casefold() for q in already_tried}
        seen: set[str] = set()
        out_sq: list[dict] = []
        for t in raw_tasks:
            q = (t.query or "").strip()
            if not q:
                continue
            k = q.casefold()
            if k in seen or k in tried_lower:
                continue
            seen.add(k)
            g = (t.goal or "").strip() or f"Follow-up angle: {q[:120]}"
            ro = (t.research_objective or "").strip()
            if not ro:
                ro = (
                    f"This follow-up targets a gap the first pass missed ({g}). "
                    f"Collect evidence that, together with prior results, better answers the original question."
                )
            out_sq.append({"query": q, "goal": g[:400], "research_objective": ro[:2000]})
        if not out_sq:
            return None
        return {
            "sub_queries": out_sq,
            "rationale": rationale_text or "Follow-up search tasks generated by the planner.",
            "source": "deep_reasoning_researcher_followup_planner",
        }
    except Exception as e:
        logger.debug("plan_followup_tasks failed: %s", e)
        return None


_CRITIC_SYSTEM = """You are a research quality critic (DeepReason-style).
You only judge whether the *gathered* titles/snippets are enough to answer the user's
question well—not whether the answer was written. Score completeness from 0 (nothing
usable) to 1 (material is enough to answer fully).

Set need_more_information=true only when important aspects of the original question are
still uncovered by these snippets. If completeness_0_1 is 0.75 or higher, default to
need_more_information=false unless you can name a specific missing facet that search could fix."""


def evaluate_research_completeness(
    original_query: str,
    research_digest: str,
    client: Any,
    heuristic: dict[str, float | int],
) -> dict:
    """
    Returns a dict safe to JSON-serialize into v4.research_completeness, including plain-English
    `tips` for UI hovers.
    """
    h_n = int(heuristic.get("n_subqueries", 0) or 0)
    h_ok = int(heuristic.get("subqueries_met_floor", 0) or 0)
    h_mean = float(heuristic.get("mean_best_relevance", 0.0) or 0.0)
    h_gaps = int(heuristic.get("gap_count", 0) or 0)

    def _heuristic_payload() -> dict:
        free_ratio = (h_ok / h_n) if h_n > 0 else 0.0
        score_01 = round(min(1.0, max(0.0, 0.45 * free_ratio + 0.55 * h_mean)), 3)
        need = bool(h_gaps > 0 or score_01 < 0.68)
        tips = {
            "completeness_percent": (
                "Estimated share of the research question that the current free hits could "
                "support, before writing an answer. "
                "This mode does not call the critic LLM (no OpenAI key or critic failed)."
            ),
            "completeness_how": (
                "Heuristic blend, plain English: we take the fraction of sub-queries that met "
                "their quality floor (each hit’s best relevance vs. that sub-query’s threshold) "
                "and multiply it by 0.45, then add 0.55 times the average of each sub-query’s "
                "best free-hit relevance score. That gives a 0–100% gauge. "
                f"Here: {h_ok}/{h_n} sub-queries met the floor → {free_ratio:.0%} coverage mix; "
                f"average best relevance ≈ {h_mean:.2f}. "
                "So the percentage is a mechanical estimate, not a human judgment."
            ),
            "need_more": (
                "Whether more web search is likely needed before you could answer confidently."
            ),
            "need_more_how": (
                "In heuristic mode we set this to yes if any sub-query is still in a “gap” "
                "(best free relevance below its floor) or if the blended completeness score "
                f"is below about 68%. Gaps now: {h_gaps}. "
                "With an API key, the critic LLM can override this using the same digest."
            ),
        }
        return {
            "mode": "heuristic",
            "completeness_score_0_1": score_01,
            "completeness_percent": round(100.0 * score_01, 1),
            "need_more_information": need,
            "critic_summary": (
                f"Heuristic: {h_ok}/{h_n} sub-queries met floor; "
                f"avg best relevance {h_mean:.2f}; {h_gaps} gap(s)."
            ),
            "tips": tips,
            "framework_ref": FRAMEWORK_URL,
        }

    if client is None or not (research_digest or "").strip():
        return _heuristic_payload()

    try:
        from pydantic import BaseModel, Field  # type: ignore

        class CriticOut(BaseModel):
            completeness_0_1: float = Field(ge=0.0, le=1.0)
            need_more_information: bool
            summary: str = Field(description="One or two sentences, plain language")

        user_msg = f"""Original question:
{original_query.strip()}

Research gathered so far (web search titles and snippets only):
{research_digest[:14000]}

Rate how sufficient this material is for answering the original question comprehensively.
Be consistent: high completeness (e.g. ≥0.75) should usually pair with need_more_information=false
unless a concrete angle is still missing from the digest."""

        out = client.chat.completions.create(
            model="gpt-4o-mini",
            response_model=CriticOut,
            messages=[
                {"role": "system", "content": _CRITIC_SYSTEM},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.1,
            timeout=16,
        )
        s01 = float(out.completeness_0_1)
        s01 = min(1.0, max(0.0, s01))
        # Align flag with structural coverage: if every sub-query met the free-tier floor,
        # extra fan-out would not address a "gap" — avoid showing "Yes" alongside high %.
        need = bool(out.need_more_information)
        if h_gaps == 0 and s01 >= 0.78:
            need = False
        tips = {
            "completeness_percent": (
                "The critic model’s 0–100% judgment of whether the titles and snippets you "
                "already pulled are enough to answer the user’s question well. "
                "It does not score writing quality—only sufficiency of gathered evidence."
            ),
            "completeness_how": (
                "Computed by a small LLM (gpt-4o-mini) with structured output. It reads your "
                "original question plus a digest built from each sub-query’s search hits "
                "(titles and snippets). It returns a single number from 0 to 1, which we show "
                "as a percent. This follows the “critic” step in deep_reasoning_researcher: "
                "evaluate completeness before treating research as done. "
                "If the API call fails, the UI falls back to the heuristic formula described "
                "in the other tooltip."
            ),
            "need_more": (
                "Whether the critic thinks another search pass (or a different angle) is "
                "still required for a complete answer."
            ),
            "need_more_how": (
                "The critic sets yes/no from the digest. After the call, we force “no” when "
                "every sub-query already met its free-tier quality floor (no coverage gaps) "
                "and completeness is ≥78%, so you do not see “more info needed” with nowhere "
                "structural left to search. Re-fan-out (extra sub-queries) runs at most once "
                "per Optimize when the interim critic said yes—see MAX_REFANOUT_ROUNDS."
            ),
        }
        return {
            "mode": "llm",
            "completeness_score_0_1": round(s01, 3),
            "completeness_percent": round(100.0 * s01, 1),
            "need_more_information": need,
            "critic_summary": (out.summary or "").strip() or "—",
            "tips": tips,
            "framework_ref": FRAMEWORK_URL,
        }
    except Exception as e:
        logger.debug("evaluate_research_completeness LLM failed: %s", e)
        return _heuristic_payload()
